version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/filiicodex/rootfs/opt/filiicodex"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/filiicodex"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
